### PR TITLE
Add Copy&Paste capability on MacOS

### PR DESCRIPTION
**Pull request by rsoutar**
There's a problem with Electron on MacOS that it cannot copy (wallet ID) or paste once it's been built. So I have added a copy&paste capability to it.

### CODE REVIEW

**Comment by Akuukis** [comment]
Thanks for contribution! My suggestions:
- does it work also without the added example menu item? If so, please remove it.
- run `yarn add electron-default-menu` to fix ordering in `package.json` and update `yarn.lock`.
- run `yarn lintfix` to auto-fix linting problems.

**Comment by rsoutar** [comment]
- Yes. it will worked but `yarn lintfix` will fail.
- Done running `yarn add electron-default-menu`
- Done running `yarn lintfix`

**Comment by Akuukis** [comment]
Looks like removed example and `yarn lintfix` changes are not commited yet. Is that coming later?

**Comment by Akuukis** [comment]
Thanks for contribution, I have fixed & rebased your suggestion into #265 at commit b05252b . I think we can close this PR now

**Pull request closed without merging**
